### ISSUE TITLE
Error No such device on PI4 Buster

### ISSUE THREAD

**Issue by ArJay60** [bablokb/pi-btaudio#3]
Is this also working on PI4 with Buster? Do get error:
ALSA lib bluealsa-pcm.c:763:(_snd_pcm_bluealsa_open) Couldn't get BlueALSA PCM: PCM not found
aplay: main:828: audio open error: No such device

**Comment by bablokb** [comment]
please verify that blue-alsa is up and running

**Comment by ArJay60** [comment]
bluealsa is running:
ps -ef | grep blue -->

root       473     1  0 20:09 ?        00:00:00 /usr/lib/bluetooth/bluetoothd
root       477     1  0 20:09 ?        00:00:00 /usr/bin/bluealsa

Any idea?

ps. There is an error in your instruction for installing:
git clone https://github.com/bablokb/pi-bt-audio.git
should be:
git clone https://github.com/bablokb/pi-btaudio.git

**Comment by bablokb** [comment]
I could reproduce your error in two circumstances:

- after fiddeling around with one of the bluetooth-services, e.g. bluetooth.service, bluealsa.service, bthelper@.service. The error was fixed after a reboot.
- the BT-speaker was not connected

Otherwise, this works with Pi4 on Buster. Having said this, I did not manage to make it work with any user except root. aplay or mpg123 just happily pretend to play without any error message, but no sound. No idea what is going on here, but other users have reported the same problem.

ps: I fixed the instructions - thanks for the hint

Bernhard

**Comment by ArJay60** [comment]
Problem is more or less solved. I can get it working but the BT disconnects after a short time. If I actively use it even earlier. A problem PI4 seems to have more often. So the problem is BT speaker not connected. I can use aplay as user pi after adding pi to the bluetooth group. Maybe you can confirm?
